# Site Settings
title: Matthew Pileggi
email: mpileggi@ufl.edu
description: molecular biology, microbial ecology, genomics, bioinformatics
baseurl: ""
url: ""
twitter_username: mattpileggi
github_username:  matthewpileggi

# Fields minima uses, but are not defaulted with the jekyll new command.
linkedin_username: matthewpileggi
author.name: Matthew Pileggi

# New fields not defaulted by jekyll-new with the minima theme go below.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
