# Site Settings
title: Matthew Pileggi
email: mpileggi@ufl.edu
description: molecular biology, microbial ecology, genomics, bioinformatics
baseurl: ""
url: ""
twitter_username: mattpileggi
github_username:  matthewpileggi

# Fields minima uses, but are not defaulted with the jekyll new command.
linkedin_username: matthewpileggi
author.name: Matthew Pileggi

# New fields not defaulted by jekyll-new with the minima theme go below.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
prose:
  rooturl: '_posts'
  siteurl: 'http://matthewpileggi.github.io/'
  relativeLinks: 'http://matthewpileggi.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
